version: '3.4'
services:
  weaviate:
    volumes:
      - /var/weaviate:/var/lib/weaviate
    image: semitechnologies/weaviate:1.19.2
    restart: on-failure:0
    ports:
     - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 100
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      DEFAULT_VECTORIZER_MODULE:  text2vec-openai
      ENABLE_MODULES:  text2vec-openai
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      OPENAI_APIKEY: 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
      CLUSTER_HOSTNAME: 'node1'
  # t2v-transformers:
  #   image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
  #   environment:
  #     ENABLE_CUDA: 0 # set to 1 to enable
      # NVIDIA_VISIBLE_DEVICES: all # enable if running with CUDA